---

  #https://stackoverflow.com/questions/26422763/how-to-create-a-new-key-in-ansible-using-the-ec2-key-module

  #Create a new EC2 keypair for us-east-2 region
  - name: Create a new EC2 key pair for us-east-2 region
    ec2_key:
      name: aws-i1-key
      region: "us-east-2"
      aws_access_key: "{{ lookup('ini', 'aws_access_keyID section=aws file=./credentials.ini') }}"
      aws_secret_key: "{{ lookup('ini', 'aws_secret_key section=aws file=./credentials.ini') }}"
    become: yes
    register: ec2key

  - name: save private key
    copy:
      content: "{{ ec2key.key.private_key }}"
      dest: "/home/ubuntu/post_build/aws-i1-key.pem"
      mode: 0600
    become: yes
    when: ec2key.changed

#https://docs.ansible.com/ansible/2.5/user_guide/playbooks_loops.html
  - include_tasks: multiple.yml
    loop:
      - 1
      - 2
      - 3
      - 4
      - 5
