- set_fact:
    outer_item: "{{ item }}"
#http://docs.ansible.com/ansible/latest/ec2_module.html
#Creating a new EC2 instance in us-east-2 region
- name: Creating a new EC2 instance in us-east-2 region
  ec2:
    key_name: aws-i1-key
    group: devops_m1
    aws_access_key: "{{ lookup('ini', 'aws_access_keyID section=aws file=./credentials.ini') }}"
    aws_secret_key: "{{ lookup('ini', 'aws_secret_key section=aws file=./credentials.ini') }}"
    instance_type: t2.micro
    # image: ami-965e6bf3      #Ubuntu Server 16.04 LTS (HVM)
    image: ami-f0f8d695       #Ubuntu Server 14.04
    region: us-east-2
    #state: present
    wait: yes
    wait_timeout: 500
    count: 1
    instance_tags:
      Name: ec2_iTrust{{ outer_item }}
  become: yes
  register: ec2

#https://www.agix.com.au/build-an-ec2-using-ansible-step-by-step/
- name: Adding the public IP address of EC2 instance in the inventory
  lineinfile:
    path: /home/ubuntu/post_build/itrust_inventory
    regexp: "{{ item.public_ip }}"
    insertafter: "[iTrust]"
    line: "{{ item.public_ip }} ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/post_build/aws-i1-key.pem"
  become: yes
  with_items: "{{ ec2.instances }}"

- name: Adding the public IP address of EC2 instance in the monitoring server
  replace:
    path: /home/ubuntu/post_build/Monitoring/main.js
    regexp: "<ITRUST-IP-{{ outer_item }}>"
    replace: "{{ item.public_ip }}:8080/iTrust2/login"
  become: yes
  with_items: "{{ ec2.instances }}"


- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  become: yes
  with_items: "{{ ec2.instances }}"
