---
- name: Copy the files needed to run iTrust and Checkboxio through Jenkins
  synchronize:
    src: ./post_build
    dest: ./
    recursive: yes

- name: copy Github private ssh key
  copy:
    src: ./roles/SetupJenkins/tasks/id_rsa
    dest: ./post_build/roles/iTrustAppSetup/tasks/id_rsa

- name: Copy Github credentials template
  copy:
    src: ./roles/SetupJenkins/templates/ssh_config.j2
    dest: ./post_build/roles/iTrustAppSetup/templates/ssh_config.j2

- name: Copy Github credentials template
  copy:
    src: ./credentials.ini
    dest: ./post_build/credentials.ini

- name: Copy ssh config
  copy:
    src: ./config
    dest: ~/.ssh/config
    mode: 0644
  become: yes

- name: Copy the public IP address of ec2 instance
  copy:
    src: ./postVars
    dest: ./post_build/group_vars/all/main.yml
