apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkbox-deployment
  labels:
    app: checkbox6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkbox6
  template:
    metadata:
      labels:
        app: checkbox6
    spec:
      containers:
      - name: checkbox6
        image: nehasak30/cbtest6
        ports:
        - containerPort: 80
        - containerPort: 3002
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017