version: '2'
services:
 mongo:
   image: frodenas/mongodb 
   environment:
     - MONGODB_USERNAME=<your MONGODB_USERNAME>
     - MONGODB_PASSWORD=<your MONGODB_PASSWORD>
 checkbox:
   image: <docker_hub_username>/cbtest6
   build: 
     context: ./checkboxApp
   environment:
     - MONGO_PORT=3002
     - MONGO_IP=mongo
     - MONGO_USER=<your_MONGODB_USERNAME>
     - MONGO_PASSWORD=<your_MONGODB_PASSWORD>
     - MAIL_USER=<your_mail_user>
     - MAIL_PASSWORD=<your_mail_password>
     - MAIL_SMTP=smtp.gmail.com
   ports:
     - "80:80"
     - "3002:3002"
   depends_on:
     - mongo