---
- hosts: jenkins
  gather_facts: no
  roles:
    - dependencies
    - post-ec2-instance-checkBox


- name: Configure checkBox EC2 instance
  hosts: checkbox
  become: yes
  gather_facts: no
  roles:
    - bootstrap
    - CBDependencies

- name: Configure MongoDB Instance
  hosts: loadBalancer
  become: yes
  gather_facts: no
  roles:
    - bootstrap
    - MongoInstance
    - canaryRelease

- name: Configure checkbox
  hosts: checkbox
  become: yes
  gather_facts: no
  roles:
    - CBSetup
