---
- name: Add mysql repo
  get_url:
    url: https://dev.mysql.com/get/mysql-apt-config_0.8.9-1_all.deb
    dest: "{{home_dir}}"
    mode: 0440
  become: true

- name: Install mysql repo
  apt: "deb={{home_dir}}/mysql-apt-config_0.8.9-1_all.deb"
  become: true

- name: Install python-mysqldb
  apt:
    name: python-mysqldb
    state: present
    update_cache: yes
  become: true

- name: Install mysql 5.7
  apt:
    name: mysql-server
    state: present
    update_cache: yes
  become: true

- name: Update mysql root password for all root accounts
  become: true
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_pass }}"
    login_user: root
    login_password: "{{ mysql_pass }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Remove a .deb package
  file:
    path: "{{home_dir}}/mysql-apt-config_0.8.9-1_all.deb"
    state: absent
    mode: 0440

- name: Start the MySQL service
  become: true
  service:
    name: mysql
    state: started
    enabled: true
